export const FactureStatus = {
  PENDING: "En attente",
  APPROVED_ADMINISTRATIF: "Accepté",
  REFUSED: "Refusé",
  IN_INSTANCE: "En instance",
  APPROVED_DAF: "Accepté",
  IN_INSTANCE_DAF: "En instance",
  COMPTABILISED: "Accepté ",
  APPROVED_FISCAL: "Accepté",
  APPROVED_PAYMENT: "Accepté",
  APPROVED_SERVICE_FINANCIAL: "Accépte",

  FINAL_APPROVED: "Accepté",
  FINAL_APPROVED_OFFICE_ORDER: "Validé",
};
export const SERVICES = {
  OFFICE_ORDER: "OFFICE_ORDER",
  ADMINISTRATIVE_DEPARTMENT: "ADMINISTRATIVE_DEPARTMENT",
  FINANCIAL_DIRECTION: "FINANCIAL_DIRECTION",
  ACCOUNTING_DEPARTMENT: "ACCOUNTING_DEPARTMENT",
  TAX_DEPARTMENT: "TAX_DEPARTMENT",
  SCHEDILING_SERVICE: "SCHEDILING_SERVICE",
  FINANCIAL_SERVICE: "FINANCIAL_SERVICE",
  EXECUTIVE_MANAGMENT: "EXECUTIVE_MANAGMENT",
};
export const LocationServices = {
  OFFICE_ORDER: "B.O.C",
  ADMINISTRATIVE_DEPARTMENT: "Service administartif",
  FINANCIAL_DIRECTION: "Direction administrative financiere",
  ACCOUNTING_DEPARTMENT: "Service comptabilité",
  TAX_DEPARTMENT: "Service fiscalité",
  SCHEDILING_SERVICE: "Service d'ordonnacement",
  FINANCIAL_SERVICE: "Service financier",
  EXECUTIVE_MANAGMENT: "direction generale",
};
